name: lk3rd CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Disable man-db update
      run: sudo rm -f /var/lib/man-db/auto-update

    - name: Install dependencies
      run: sudo apt install mkbootimg gcc-aarch64-linux-gnu build-essential

    - name: Build the project for all devices
      run: ./lk3rd-build-all.sh
